name: frontend_hackathon_mobile
description: "Fiap Hackathon - MindEase Mobile"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8
  flutter: ^3.41.1

platforms:
  android:
  web:

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  http: ^1.6.0
  provider: ^6.1.5+1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/hero_banner.png
    - assets/images/not_found.png
    - assets/logos/logo_desktop.png
    - assets/logos/logo_mobile.png
